package localux.view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class AuSujet extends javax.swing.JFrame {

    /**
     * Creates new form About
     */
    public AuSujet() {
        String[] dataSys = {"java.version", "java.version.date", "java.vendor", "java.vendor.url", "java.vendor.version", "java.home",
            "java.vm.specification.version", "java.vm.specification.vendor", "java.vm.specification.name", "java.vm.version", "java.vm.vendor",
            "java.vm.name", "java.specification.version", "java.specification.vendor", "java.specification.name", "java.class.version",
            "java.class.path", "java.library.path", "java.io.tmpdir", "java.compiler", "os.name", "os.arch", "os.version", "file.separator",
            "path.separator", "line.separator", "user.name", "user.home", "user.dir"};

        initComponents();
        tableVarSys.setDefaultRenderer(Object.class, new localux.technic.CTableRendu());
        scrollDataSys.getViewport().setOpaque(false);
        
        JTableHeader tableHead = tableVarSys.getTableHeader();
        Font f = tableHead.getFont();
        tableHead.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
        tableHead.setForeground(new Color(191, 0, 24));



        DefaultTableModel uiTable = (DefaultTableModel) tableVarSys.getModel();
        Object[] row = new Object[2];
        for (String uneVar : dataSys) {
            row[0] = uneVar;
            row[1] = System.getProperty(uneVar);
            uiTable.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entete = new javax.swing.JPanel();
        logoLCN = new javax.swing.JLabel();
        titreGen = new javax.swing.JLabel();
        adresse = new javax.swing.JLabel();
        scrollDataSys = new javax.swing.JScrollPane();
        tableVarSys = new javax.swing.JTable();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("view.auSujet");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(730, 620));
        getContentPane().setLayout(null);

        entete.setBackground(new java.awt.Color(255, 255, 255));
        entete.setOpaque(false);

        logoLCN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLCN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/btslcn_x100.png"))); // NOI18N

        titreGen.setBackground(new java.awt.Color(255, 255, 255));
        titreGen.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        titreGen.setForeground(new java.awt.Color(252, 220, 49));
        titreGen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreGen.setText("Projet client lourd et ressources en Java");
        titreGen.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        adresse.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        adresse.setForeground(new java.awt.Color(252, 220, 49));
        adresse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adresse.setText("<html><center>BTS SIO SLAM<br>\n\nLycée Claude Nougaro<br>\n\n82300 MONTEILS</center></html>"); // NOI18N

        javax.swing.GroupLayout enteteLayout = new javax.swing.GroupLayout(entete);
        entete.setLayout(enteteLayout);
        enteteLayout.setHorizontalGroup(
            enteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enteteLayout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addComponent(titreGen, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(enteteLayout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(logoLCN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(enteteLayout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        enteteLayout.setVerticalGroup(
            enteteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enteteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titreGen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoLCN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adresse, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(entete);
        entete.setBounds(0, 0, 730, 235);

        scrollDataSys.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        scrollDataSys.setOpaque(false);

        tableVarSys.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tableVarSys.setForeground(new java.awt.Color(255, 255, 255));
        tableVarSys.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VARIABLE SYSTÈME", "CONTENU DE LA VARIABLE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVarSys.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tableVarSys.setGridColor(new java.awt.Color(255, 255, 255));
        tableVarSys.setOpaque(false);
        tableVarSys.getTableHeader().setResizingAllowed(false);
        tableVarSys.getTableHeader().setReorderingAllowed(false);
        scrollDataSys.setViewportView(tableVarSys);
        if (tableVarSys.getColumnModel().getColumnCount() > 0) {
            tableVarSys.getColumnModel().getColumn(0).setResizable(false);
            tableVarSys.getColumnModel().getColumn(0).setPreferredWidth(242);
            tableVarSys.getColumnModel().getColumn(1).setResizable(false);
            tableVarSys.getColumnModel().getColumn(1).setPreferredWidth(460);
        }

        getContentPane().add(scrollDataSys);
        scrollDataSys.setBounds(0, 241, 730, 320);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/fec_dark.jpg"))); // NOI18N
        getContentPane().add(fond);
        fond.setBounds(0, 0, 730, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuSujet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuSujet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresse;
    private javax.swing.JPanel entete;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel logoLCN;
    private javax.swing.JScrollPane scrollDataSys;
    private javax.swing.JTable tableVarSys;
    private javax.swing.JLabel titreGen;
    // End of variables declaration//GEN-END:variables
}
