package localux.view;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Statement;
import java.util.TreeMap;
import localux.DAO.photoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import localux.model.Utilisateur;
import localux.DAO.UtilisateurDAO;
import localux.model.Commune;
import javax.swing.table.JTableHeader;
import localux.model.Photo;
import localux.model.LocationSansChauffeur;
/**
 *
 * @author Patrick DUPRE
 */
public class ListLocation extends javax.swing.JFrame {
    
    private final Utilisateur utConnect;

    /**
     * Creates new form UtilCrud
     */
    Connection con;
    Statement st;
    //LinkedList<Utilisateur> lesUtilisateurs = new LinkedList<>();
    TreeMap<String, Utilisateur> lesUtilisateurs = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
    UtilisateurDAO dao = new UtilisateurDAO();
    String uiNumpost;
    private Commune selectedVille;
    private Photo photo;

    public ListLocation(Utilisateur utilisateur) {
        this.utConnect = utilisateur;
        initComponents();
        tbUtilisateur.setDefaultRenderer(Object.class, new localux.technic.CTableRendu());
        tbScrollPane.getViewport().setOpaque(false);
        
        JTableHeader tableHead = tbUtilisateur.getTableHeader();
        Font f = tableHead.getFont();
        tableHead.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
        tableHead.setForeground(new Color(191, 0, 24));
        
        message.setText("Veuillez choisir un utilisateur dans le tableau de droite ou saisir les données à creer");
        chargerLesUtilisateurs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Entete = new javax.swing.JLabel();
        tbScrollPane = new javax.swing.JScrollPane();
        tbUtilisateur = new javax.swing.JTable();
        jPanelSaisie = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        uiLocation = new javax.swing.JTextField();
        jLabelPrenom = new javax.swing.JLabel();
        jLabelPseudo = new javax.swing.JLabel();
        jLabelMail = new javax.swing.JLabel();
        uiPhrase = new javax.swing.JLabel();
        jLabelMail1 = new javax.swing.JLabel();
        Vider = new javax.swing.JButton();
        Creer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        uiImmat = new javax.swing.JTextField();
        jLabelMail2 = new javax.swing.JLabel();
        jLabelMail3 = new javax.swing.JLabel();
        jLabelMail4 = new javax.swing.JLabel();
        jLabelMail5 = new javax.swing.JLabel();
        uiAssuranceComp = new javax.swing.JTextField();
        uiFormule = new javax.swing.JTextField();
        jLabelMail7 = new javax.swing.JLabel();
        uiDateRetourPrevu = new javax.swing.JFormattedTextField();
        uiDateDepartPrevu = new javax.swing.JFormattedTextField();
        uiCoutEstime = new javax.swing.JFormattedTextField();
        uiMontant = new javax.swing.JFormattedTextField();
        uiNbKmDepart = new javax.swing.JFormattedTextField();
        uiDateLocation = new javax.swing.JFormattedTextField();
        message = new javax.swing.JLabel();
        jPanelBt = new javax.swing.JPanel();
        Parametre = new javax.swing.JButton();
        Aide = new javax.swing.JButton();
        Quitter = new javax.swing.JButton();
        Editer = new javax.swing.JButton();
        uiBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("view.UtilCrud");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1080, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 680));
        getContentPane().setLayout(null);

        Entete.setBackground(new java.awt.Color(255,255,255,120));
        Entete.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Entete.setForeground(new java.awt.Color(255, 0, 0));
        Entete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/java_64.png"))); // NOI18N
        Entete.setText("Gestion des vehicules");
        Entete.setMaximumSize(new java.awt.Dimension(1044, 70));
        Entete.setMinimumSize(new java.awt.Dimension(1044, 70));
        Entete.setOpaque(true);
        Entete.setPreferredSize(new java.awt.Dimension(1044, 70));
        getContentPane().add(Entete);
        Entete.setBounds(0, 0, 1080, 70);

        tbScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        tbScrollPane.setOpaque(false);

        tbUtilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°Location", "Date Location", "Date Depart Prévu", "Date Retour Prévu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUtilisateur.setOpaque(false);
        tbUtilisateur.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbUtilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUtilisateurMouseClicked(evt);
            }
        });
        tbUtilisateur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbUtilisateurKeyReleased(evt);
            }
        });
        tbScrollPane.setViewportView(tbUtilisateur);
        if (tbUtilisateur.getColumnModel().getColumnCount() > 0) {
            tbUtilisateur.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(tbScrollPane);
        tbScrollPane.setBounds(12, 77, 439, 460);

        jPanelSaisie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSaisie.setForeground(new java.awt.Color(252, 220, 49));
        jPanelSaisie.setOpaque(false);

        jLabelNom.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNom.setForeground(new java.awt.Color(252, 220, 49));
        jLabelNom.setText("N°Location");

        uiLocation.setBackground(new java.awt.Color(255,255,255,120));
        uiLocation.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiLocation.setForeground(new java.awt.Color(255, 255, 255));

        jLabelPrenom.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPrenom.setForeground(new java.awt.Color(252, 220, 49));
        jLabelPrenom.setText("Date Location");

        jLabelPseudo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPseudo.setForeground(new java.awt.Color(252, 220, 49));
        jLabelPseudo.setText("Montant Réglé");

        jLabelMail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMail.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMail.setText("Date Depart Prévu");

        uiPhrase.setBackground(new java.awt.Color(255, 255, 255));
        uiPhrase.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        uiPhrase.setForeground(new java.awt.Color(204, 0, 51));

        jLabelMail1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMail1.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMail1.setText("Immatriculation");

        Vider.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Vider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/eye-slash_20.png"))); // NOI18N
        Vider.setText("Nouveau");
        Vider.setToolTipText("Dé-selectionner l'utilisateur");
        Vider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViderMouseClicked(evt);
            }
        });

        Creer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Creer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/plus_20.png"))); // NOI18N
        Creer.setText("Creer");
        Creer.setToolTipText("Valider la création d'un nouvel utilisateur");
        Creer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreerMouseClicked(evt);
            }
        });

        Modifier.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/pencil_20.png"))); // NOI18N
        Modifier.setText("Modifier");
        Modifier.setToolTipText("Valider les modifications");
        Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierMouseClicked(evt);
            }
        });

        Supprimer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/minus_20.png"))); // NOI18N
        Supprimer.setText("Supprimer");
        Supprimer.setToolTipText("Supprimer l'utilisateur");
        Supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupprimerMouseClicked(evt);
            }
        });

        uiImmat.setBackground(new java.awt.Color(255,255,255,120));
        uiImmat.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiImmat.setForeground(new java.awt.Color(255, 255, 255));

        jLabelMail2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMail2.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMail2.setText("Date Retour Prévu");

        jLabelMail3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMail3.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMail3.setText("Nombre Km Depart");

        jLabelMail4.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMail4.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMail4.setText("Cout Répa Estimé");

        jLabelMail5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMail5.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMail5.setText("Assurance Complé");

        uiAssuranceComp.setBackground(new java.awt.Color(255,255,255,120));
        uiAssuranceComp.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiAssuranceComp.setForeground(new java.awt.Color(255, 255, 255));

        uiFormule.setBackground(new java.awt.Color(255,255,255,120));
        uiFormule.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiFormule.setForeground(new java.awt.Color(255, 255, 255));
        uiFormule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiFormuleActionPerformed(evt);
            }
        });

        jLabelMail7.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMail7.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMail7.setText("Formule");

        uiDateRetourPrevu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        uiDateDepartPrevu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        uiCoutEstime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        uiMontant.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        uiNbKmDepart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        uiDateLocation.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        uiDateLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiDateLocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSaisieLayout = new javax.swing.GroupLayout(jPanelSaisie);
        jPanelSaisie.setLayout(jPanelSaisieLayout);
        jPanelSaisieLayout.setHorizontalGroup(
            jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                    .addComponent(jLabelPseudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelMail2)
                                .addComponent(jLabelMail3))
                            .addComponent(jLabelMail7)
                            .addComponent(jLabelMail1)
                            .addComponent(jLabelMail4))
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(uiDateRetourPrevu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(uiDateDepartPrevu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(uiImmat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                .addComponent(uiLocation))
                                            .addComponent(uiCoutEstime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uiMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uiNbKmDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(uiDateLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uiPhrase, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(uiFormule))))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Creer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Supprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(Vider))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addComponent(jLabelMail5)
                        .addGap(18, 18, 18)
                        .addComponent(uiAssuranceComp, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSaisieLayout.setVerticalGroup(
            jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiDateLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiMontant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uiDateDepartPrevu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(uiPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMail2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiDateRetourPrevu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uiImmat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMail3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiNbKmDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uiCoutEstime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMail4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uiAssuranceComp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMail5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMail7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiFormule, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vider)
                    .addComponent(Creer)
                    .addComponent(Modifier)
                    .addComponent(Supprimer))
                .addContainerGap())
        );

        getContentPane().add(jPanelSaisie);
        jPanelSaisie.setBounds(469, 77, 580, 460);

        message.setBackground(new java.awt.Color(255, 255, 255));
        message.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        message.setForeground(new java.awt.Color(51, 102, 0));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("Message");
        getContentPane().add(message);
        message.setBounds(20, 560, 990, 19);

        jPanelBt.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBt.setMaximumSize(new java.awt.Dimension(1024, 50));
        jPanelBt.setMinimumSize(new java.awt.Dimension(1024, 50));
        jPanelBt.setOpaque(false);
        jPanelBt.setPreferredSize(new java.awt.Dimension(1010, 50));

        Parametre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Parametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/wrench._20.png"))); // NOI18N
        Parametre.setText("Paramètre");
        Parametre.setToolTipText("Paramètres de l'application");
        Parametre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParametreMouseClicked(evt);
            }
        });

        Aide.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Aide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/question-circle_20.png"))); // NOI18N
        Aide.setText("Aide");
        Aide.setToolTipText("Manuel utilisateur");
        Aide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AideMouseClicked(evt);
            }
        });

        Quitter.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/escape_20.png"))); // NOI18N
        Quitter.setText("Quitter");
        Quitter.setToolTipText("Quitter l'application");
        Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterMouseClicked(evt);
            }
        });

        Editer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Editer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/pdf_20.png"))); // NOI18N
        Editer.setText("Pdf");
        Editer.setToolTipText("Envoyer un mail à l'utilisateur");
        Editer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtLayout = new javax.swing.GroupLayout(jPanelBt);
        jPanelBt.setLayout(jPanelBtLayout);
        jPanelBtLayout.setHorizontalGroup(
            jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtLayout.createSequentialGroup()
                .addComponent(Parametre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 652, Short.MAX_VALUE)
                .addComponent(Editer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Aide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Quitter))
        );
        jPanelBtLayout.setVerticalGroup(
            jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Quitter)
                        .addComponent(Aide)
                        .addComponent(Editer))
                    .addComponent(Parametre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBt);
        jPanelBt.setBounds(10, 580, 1050, 50);

        uiBackground.setBackground(new java.awt.Color(255, 255, 255));
        uiBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/fec_dark.jpg"))); // NOI18N
        uiBackground.setIconTextGap(0);
        uiBackground.setMaximumSize(new java.awt.Dimension(1060, 660));
        uiBackground.setMinimumSize(new java.awt.Dimension(1060, 660));
        uiBackground.setPreferredSize(new java.awt.Dimension(1060, 660));
        getContentPane().add(uiBackground);
        uiBackground.setBounds(0, 0, 1080, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Positionner les valeurs de la zone de texte 
    private void tbUtilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUtilisateurMouseClicked
        // TODO add your handling code here:
        changeSelectUt();
    }//GEN-LAST:event_tbUtilisateurMouseClicked

        private void CreerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreerMouseClicked
            // TODO add your handling code here:
            // mise à jour de la liste
            if (lesUtilisateurs.get(uiModele.getText().strip()) != null) {
                alert("Utilisateur déjà existant ; veuillez choisir un autre pseudo.");
                return;
            }
            if ("".equals(uiImmat.getText().strip()) || "".equals(uiMP.getText().strip())) {
                alert("Saisir au moins un nom et un mot de passe.");
                return;
            }
            if ("".equals(uiDescription.getText().strip()) || "".equals(uiNumpost)) {
                alert("Saisir le code postal et renseigner la ville.");
                return;
            }
            
            // création de la LSC
            LocationSansChauffeur uneLSC = new LocationSansChauffeur();
            uneLSC.setNumLocation(uiLocation.getText().strip());
            uneLSC.setDateLocation(uiDateLocation.getText().strip());
            uneLSC.setMontantRegle(uiMontant.getText().strip());
            uneLSC.setNbKmDepart(uiDateDepartPrevu.getText().strip());
            uneLSC.setNbKmRetour(uiDateRetourPrevu1.getText().strip());
            uneLSC.setLaFormule(uiImmat.getText().strip());  //SET VEHICULE
            uneLSC.setNbKmDepart(uiNbKmDepart.getText().strip());
            uneLSC.setNumLocation(uiCoutEstime.getText().strip());
            uneLSC.setNumLocation(uiAssuranceComp.getText().strip());
            uneLSC.setLaFormule(uiFormule.getText().strip());

            // Ajout à la liste
            LesLocationsSansChaffeur.put(uneLSC.getUtPseudo(), uneLSC);
            // MàJ des données du tableau
            chargerTableauUtilisateurs();
            // mise à jour de la bd
            dao.create(unUtilisateur);


        }//GEN-LAST:event_CreerMouseClicked

        private void ViderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViderMouseClicked
            // TODO add your handling code here:
            tbUtilisateur.getSelectionModel().clearSelection();
            message.setText("Vous pouvez saisir un nouvel utilisateur !");
            viderSaisie();
        }//GEN-LAST:event_ViderMouseClicked

        private void QuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterMouseClicked
            // TODO add your handling code here:
           this.dispose();
        }//GEN-LAST:event_QuitterMouseClicked

        private void AideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AideMouseClicked
            // TODO add your handling code here:
        }//GEN-LAST:event_AideMouseClicked

        private void ParametreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParametreMouseClicked
            // TODO add your handling code here:
            Parametre parametre = new Parametre(this.utConnect);
            parametre.setVisible(true);
        }//GEN-LAST:event_ParametreMouseClicked

        private void ModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierMouseClicked
            // TODO add your handling code here:

            // mise à jour de la liste
            int i = tbUtilisateur.getSelectedRow();
            if (i < 0) {
                alert("Aucune donnée n'est selectionnée en modification ; veuillez choisir un utilisateur.");
                return;
            }
            TableModel model = tbUtilisateur.getModel();
            Utilisateur unUtilisateur = lesUtilisateurs.get(model.getValueAt(i, 2).toString().strip());
            if (!unUtilisateur.getUtPseudo().equals(uiModele.getText().strip())) {
                alert("Vous ne pouvez pas modifier le pseudo de l'utilisateur (creez en un autre puis supprimez l'ancien). ("
                        + unUtilisateur.getUtPseudo() + "/" + uiModele.getText().strip() + ")");
                return;
            }
            // le mot de passe a t-il changé ?
            if (!unUtilisateur.getUtMp().equals(uiMP.getText().strip())) {
                System.out.println("\n 1=" + unUtilisateur.getUtMp() + "\n 2=" + uiMP.getText().strip());
                unUtilisateur.updateUtMp(uiMP.getText().strip());
                uiPhrase.setText(unUtilisateur.getUtPhrase());
            }
            // MàJ les données de l'objet utilisateur
            unUtilisateur.setUtNom(uiImmat.getText().strip());
            unUtilisateur.setUtPrenom(uiDateAchat.getText().strip());
            unUtilisateur.setUtMail(uiTarif.getText().strip());
            //unUtilisateur.setUtMp(uiMP.getText().strip());
            unUtilisateur.setUtAdr1(uiAdr1.getText().strip());
         //   unUtilisateur.setUtAdr2(uiAdr2.getText().strip());
            unUtilisateur.utCommune.setCode_Postal(uiDescription.getText().strip());
            unUtilisateur.utCommune.setNum_Postal(uiNumpost);
        //    unUtilisateur.utCommune.setNom_Commune(uiCommune.getText());
            // MàJ des données du tableau
            model.setValueAt(uiImmat.getText(), i, 0);
            model.setValueAt(uiDateAchat.getText(), i, 1);
            // mise à jour de la bd
            dao.update(unUtilisateur);

        }//GEN-LAST:event_ModifierMouseClicked

    private void tbUtilisateurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbUtilisateurKeyReleased
        // TODO add your handling code here:
        changeSelectUt();
    }//GEN-LAST:event_tbUtilisateurKeyReleased

    private void SupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupprimerMouseClicked
        // TODO add your handling code here:
        int i = tbUtilisateur.getSelectedRow();
        if (i < 0) {
            alert("Aucune donnée n'est selectionnée; veuillez selectionner l'utilisateur a supprimer.");
            return;
        }
        DefaultTableModel uiTable = (DefaultTableModel) tbUtilisateur.getModel();
        String pseudo = uiTable.getValueAt(i, 2).toString();
        // mise à jour de la bd
        dao.delete(pseudo);
        uiTable.removeRow(i);
        lesUtilisateurs.remove(pseudo);
        viderSaisie();
    }//GEN-LAST:event_SupprimerMouseClicked

    private void EditerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditerMouseClicked

    private void uiFormuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiFormuleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiFormuleActionPerformed

    private void uiDateLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiDateLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiDateLocationActionPerformed

    // methode pour changer d'utilisateur
    public void changeSelectUt() {
        // pointer sur le colonne selectionnée
        int i = tbUtilisateur.getSelectedRow();
        //System.out.println("selected row=" + i);
        // récupérer les données de l'utilisateur
        // utiliser les données du tableau ou ...
        TableModel model = tbUtilisateur.getModel();
        Utilisateur unUtilisateur = lesUtilisateurs.get(model.getValueAt(i, 2).toString());
        uiImmat.setText(unUtilisateur.getUtNom());
        uiDateAchat.setText(unUtilisateur.getUtPrenom());
        uiModele.setText(unUtilisateur.getUtPseudo());
        uiTarif.setText(unUtilisateur.getUtMail());
        uiMP.setText(unUtilisateur.getUtMp());
        uiPhrase.setText(unUtilisateur.getUtPhrase());
        uiAdr1.setText(unUtilisateur.getUtAdr1());
    //    uiAdr2.setText(unUtilisateur.getUtAdr2());
        uiDescription.setText(unUtilisateur.utCommune.getCode_Postal());
        uiNumpost = unUtilisateur.utCommune.getNum_Postal();
    //    uiCommune.setText(unUtilisateur.utCommune.getNom_Commune());
    }

    // methode pour afficher un message
    public void alert(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
        message.setForeground(new java.awt.Color(51, 102, 0));
        message.setText(msg);
    }

    // methode  to show an error alert
    public void alert(String msg, String titre) {
        JOptionPane.showMessageDialog(rootPane, msg, titre, JOptionPane.ERROR_MESSAGE);
        message.setForeground(new java.awt.Color(204, 0, 51));
        message.setText(msg);
    }

    //delete details in the db
    public void delete(String pseudo) {

    }

    // methode pour vider les champs de texte de l'écran
    private void viderSaisie() {
        uiImmat.setText("");
        uiDateAchat.setText("");
        uiModele.setText("");
        uiTarif.setText("");
        uiMP.setText("");
        uiPhrase.setText("");
        uiAdr1.setText("");
    //    uiAdr2.setText("");
        uiDescription.setText("");
        uiNumpost = "";
    //    uiCommune.setText("");
        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie-min.jpg")));

    }

    // chargerLesUtilisateurs 
    private void chargerLesUtilisateurs() {

        lesUtilisateurs.clear();
        lesUtilisateurs = UtilisateurDAO.getLesUtilisateurs();
        chargerTableauUtilisateurs();
    }

    private void chargerTableauUtilisateurs() {

        DefaultTableModel uiTable = (DefaultTableModel) tbUtilisateur.getModel();
        int j = uiTable.getRowCount();
        //System.out.println("Row count=" + j);
        for (int i = j - 1; i >= 0; i--) {
            //System.out.println("Row remove=" + i);
            uiTable.removeRow(i);
        }
        int i = 0;
        for (String pseudo : lesUtilisateurs.keySet()) {
            Utilisateur unUtilisateur = lesUtilisateurs.get(pseudo);
            Object[] row = new Object[3];
            row[0] = unUtilisateur.getUtNom();
            row[1] = unUtilisateur.getUtPrenom();
            row[2] = unUtilisateur.getUtPseudo();

            uiTable.addRow(row);
            if(pseudo.equals(uiModele.getText().strip())) {
                tbUtilisateur.setRowSelectionInterval(i, i);
            }
            i++;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aide;
    private javax.swing.JButton Creer;
    private javax.swing.JButton Editer;
    private javax.swing.JLabel Entete;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Parametre;
    private javax.swing.JButton Quitter;
    private javax.swing.JButton Supprimer;
    private javax.swing.JButton Vider;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMail1;
    private javax.swing.JLabel jLabelMail2;
    private javax.swing.JLabel jLabelMail3;
    private javax.swing.JLabel jLabelMail4;
    private javax.swing.JLabel jLabelMail5;
    private javax.swing.JLabel jLabelMail7;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelPseudo;
    private javax.swing.JPanel jPanelBt;
    private javax.swing.JPanel jPanelSaisie;
    private javax.swing.JLabel message;
    private javax.swing.JScrollPane tbScrollPane;
    private javax.swing.JTable tbUtilisateur;
    private javax.swing.JTextField uiAssuranceComp;
    private javax.swing.JLabel uiBackground;
    private javax.swing.JFormattedTextField uiCoutEstime;
    private javax.swing.JFormattedTextField uiDateDepartPrevu;
    private javax.swing.JFormattedTextField uiDateLocation;
    private javax.swing.JFormattedTextField uiDateRetourPrevu;
    private javax.swing.JTextField uiFormule;
    private javax.swing.JTextField uiImmat;
    private javax.swing.JTextField uiLocation;
    private javax.swing.JFormattedTextField uiMontant;
    private javax.swing.JFormattedTextField uiNbKmDepart;
    private javax.swing.JLabel uiPhrase;
    // End of variables declaration//GEN-END:variables
}
