package localux.view;

import localux.model.Utilisateur;

public class MainMenu extends javax.swing.JFrame {

    private final Utilisateur utConnect;

    /**
     * Creates new form mail
     *
     * @param utilisateur
     */
    public MainMenu(Utilisateur utilisateur) {
        this.utConnect = utilisateur;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Entete = new javax.swing.JLabel();
        parametrer = new javax.swing.JLabel();
        Clients = new javax.swing.JLabel();
        mailler = new javax.swing.JLabel();
        Vehicle = new javax.swing.JLabel();
        dashboard = new javax.swing.JLabel();
        imprime = new javax.swing.JLabel();
        quitte = new javax.swing.JLabel();
        info = new javax.swing.JButton();
        abandon = new javax.swing.JButton();
        uiBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("view.MainMenu");
        setMinimumSize(new java.awt.Dimension(700, 470));
        setResizable(false);
        getContentPane().setLayout(null);

        Entete.setBackground(new java.awt.Color(255,255,255,120));
        Entete.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Entete.setForeground(new java.awt.Color(255, 0, 0));
        Entete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/java_64.png"))); // NOI18N
        Entete.setText(" Menu général");
        Entete.setIconTextGap(22);
        Entete.setOpaque(true);
        getContentPane().add(Entete);
        Entete.setBounds(0, 0, 699, 71);

        parametrer.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        parametrer.setForeground(new java.awt.Color(204, 204, 204));
        parametrer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        parametrer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/gear_80.png"))); // NOI18N
        parametrer.setText("Paramètres");
        parametrer.setToolTipText("Paramétrer l'application");
        parametrer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        parametrer.setIconTextGap(0);
        parametrer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        parametrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parametrerMouseClicked(evt);
            }
        });
        getContentPane().add(parametrer);
        parametrer.setBounds(140, 240, 100, 100);

        Clients.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Clients.setForeground(new java.awt.Color(204, 204, 204));
        Clients.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Clients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/user-secret_80.png"))); // NOI18N
        Clients.setText("Clients");
        Clients.setToolTipText("Gestion des utilisateurs");
        Clients.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Clients.setIconTextGap(0);
        Clients.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Clients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientsMouseClicked(evt);
            }
        });
        getContentPane().add(Clients);
        Clients.setBounds(60, 110, 100, 100);

        mailler.setBackground(new java.awt.Color(255, 255, 255,100));
        mailler.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        mailler.setForeground(new java.awt.Color(204, 204, 204));
        mailler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mailler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/envelope_80.png"))); // NOI18N
        mailler.setText("Mail");
        mailler.setToolTipText("Envoyer un Mail");
        mailler.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mailler.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mailler.setIconTextGap(0);
        mailler.setMaximumSize(new java.awt.Dimension(80, 100));
        mailler.setMinimumSize(new java.awt.Dimension(80, 100));
        mailler.setPreferredSize(new java.awt.Dimension(80, 100));
        mailler.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        mailler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maillerMouseClicked(evt);
            }
        });
        getContentPane().add(mailler);
        mailler.setBounds(310, 240, 100, 100);

        Vehicle.setBackground(new java.awt.Color(255, 255, 255,100));
        Vehicle.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Vehicle.setForeground(new java.awt.Color(204, 204, 204));
        Vehicle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Vehicle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/white-car-back.png"))); // NOI18N
        Vehicle.setText("Vehicules");
        Vehicle.setToolTipText("Gérer les données");
        Vehicle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Vehicle.setIconTextGap(0);
        Vehicle.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Vehicle.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                VehicleAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        Vehicle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VehicleMouseClicked(evt);
            }
        });
        getContentPane().add(Vehicle);
        Vehicle.setBounds(220, 110, 100, 100);

        dashboard.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        dashboard.setForeground(new java.awt.Color(204, 204, 204));
        dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/white-clipboard-list.png"))); // NOI18N
        dashboard.setText("Location");
        dashboard.setToolTipText("Tableau de bord");
        dashboard.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dashboard.setIconTextGap(0);
        dashboard.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });
        getContentPane().add(dashboard);
        dashboard.setBounds(380, 110, 100, 100);

        imprime.setBackground(new java.awt.Color(255, 255, 255,100));
        imprime.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        imprime.setForeground(new java.awt.Color(204, 204, 204));
        imprime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imprime.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/white-file-document.png"))); // NOI18N
        imprime.setText("Rapports");
        imprime.setToolTipText("Imprimer des données au format pdf");
        imprime.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imprime.setIconTextGap(0);
        imprime.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imprime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imprimeMouseClicked(evt);
            }
        });
        getContentPane().add(imprime);
        imprime.setBounds(540, 110, 100, 100);

        quitte.setBackground(new java.awt.Color(255, 255, 255,100));
        quitte.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        quitte.setForeground(new java.awt.Color(204, 204, 204));
        quitte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quitte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/power-off_80.png"))); // NOI18N
        quitte.setText("Déconnexion");
        quitte.setToolTipText("Se déconnecter de l'application");
        quitte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quitte.setIconTextGap(0);
        quitte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        quitte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitteMouseClicked(evt);
            }
        });
        getContentPane().add(quitte);
        quitte.setBounds(470, 240, 100, 100);

        info.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/info-circle_20.png"))); // NOI18N
        info.setText("Au Sujet");
        info.setToolTipText("Sortir de la fenétre d'envoi");
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
        });
        getContentPane().add(info);
        info.setBounds(20, 390, 105, 30);

        abandon.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        abandon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/escape_20.png"))); // NOI18N
        abandon.setText("Abandonner");
        abandon.setToolTipText("Sortir de la fenétre d'envoi");
        abandon.setOpaque(false);
        abandon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abandonMouseClicked(evt);
            }
        });
        getContentPane().add(abandon);
        abandon.setBounds(542, 390, 127, 30);

        uiBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/fec_dark.jpg"))); // NOI18N
        uiBackground.setMaximumSize(new java.awt.Dimension(700, 430));
        uiBackground.setMinimumSize(new java.awt.Dimension(700, 430));
        uiBackground.setPreferredSize(new java.awt.Dimension(700, 430));
        getContentPane().add(uiBackground);
        uiBackground.setBounds(0, 0, 700, 430);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        private void abandonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abandonMouseClicked
            // TODO add your handling code here:
            this.dispose();
        }//GEN-LAST:event_abandonMouseClicked

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked
        // TODO add your handling code here:
        AuSujet auSujet = new AuSujet();
        auSujet.setVisible(true);
    }//GEN-LAST:event_infoMouseClicked

    private void parametrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parametrerMouseClicked
        // TODO add your handling code here:
        Parametre parametre = new Parametre(this.utConnect);
        parametre.setVisible(true);
    }//GEN-LAST:event_parametrerMouseClicked

    private void maillerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maillerMouseClicked
        // TODO add your handling code here:
        Mail courriel = new Mail();
            courriel.setVisible(true);
    }//GEN-LAST:event_maillerMouseClicked

    private void VehicleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehicleMouseClicked
        // TODO add your handling code here:
        VehicleList vehicleLIST = new VehicleList (this.utConnect);
        vehicleLIST.setVisible(true);
    }//GEN-LAST:event_VehicleMouseClicked

    private void imprimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imprimeMouseClicked
        Rapport rapport = new Rapport();
        rapport.setVisible(true);
    }//GEN-LAST:event_imprimeMouseClicked

    private void quitteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitteMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_quitteMouseClicked

    private void ClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientsMouseClicked
        // TODO add your handling code here:
        UtilCrud utilCRUD = new UtilCrud(this.utConnect);
        utilCRUD.setVisible(true);
    }//GEN-LAST:event_ClientsMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        Location location = new Location();
        location.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_dashboardMouseClicked

    private void VehicleAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_VehicleAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_VehicleAncestorMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clients;
    private javax.swing.JLabel Entete;
    private javax.swing.JLabel Vehicle;
    private javax.swing.JButton abandon;
    private javax.swing.JLabel dashboard;
    private javax.swing.JLabel imprime;
    private javax.swing.JButton info;
    private javax.swing.JLabel mailler;
    private javax.swing.JLabel parametrer;
    private javax.swing.JLabel quitte;
    private javax.swing.JLabel uiBackground;
    // End of variables declaration//GEN-END:variables
}
