package localux.view;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Statement;
import java.util.TreeMap;
import localux.DAO.photoDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import localux.model.Utilisateur;
import localux.DAO.UtilisateurDAO;
import localux.model.Commune;
import javax.swing.table.JTableHeader;
import localux.model.Photo;

/**
 *
 * @author Patrick DUPRE
 */
public class VehicleList extends javax.swing.JFrame {
    
    private final Utilisateur utConnect;

    /**
     * Creates new form UtilCrud
     */
    Connection con;
    Statement st;
    //LinkedList<Utilisateur> lesUtilisateurs = new LinkedList<>();
    TreeMap<String, Utilisateur> lesUtilisateurs = new TreeMap<>(String.CASE_INSENSITIVE_ORDER);
    UtilisateurDAO dao = new UtilisateurDAO();
    String uiNumpost;
    private Commune selectedVille;
    private Photo photo;

    public VehicleList(Utilisateur utilisateur) {
        this.utConnect = utilisateur;
        initComponents();
        tbUtilisateur.setDefaultRenderer(Object.class, new localux.technic.CTableRendu());
        tbScrollPane.getViewport().setOpaque(false);
        
        JTableHeader tableHead = tbUtilisateur.getTableHeader();
        Font f = tableHead.getFont();
        tableHead.setFont(f.deriveFont(f.getStyle() | Font.BOLD));
        tableHead.setForeground(new Color(191, 0, 24));
        
        message.setText("Veuillez choisir un utilisateur dans le tableau de droite ou saisir les données à creer");
        chargerLesUtilisateurs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Entete = new javax.swing.JLabel();
        tbScrollPane = new javax.swing.JScrollPane();
        tbUtilisateur = new javax.swing.JTable();
        jPanelSaisie = new javax.swing.JPanel();
        jLabelNom = new javax.swing.JLabel();
        uiNom = new javax.swing.JTextField();
        jLabelPrenom = new javax.swing.JLabel();
        uiPrenom = new javax.swing.JTextField();
        jLabelPseudo = new javax.swing.JLabel();
        uiPseudo = new javax.swing.JTextField();
        jLabelMail = new javax.swing.JLabel();
        uiMail = new javax.swing.JTextField();
        jLabelMP = new javax.swing.JLabel();
        uiMP = new javax.swing.JTextField();
        uiPhrase = new javax.swing.JLabel();
        jLabelMail1 = new javax.swing.JLabel();
        uiAdr1 = new javax.swing.JTextField();
        Vider = new javax.swing.JButton();
        Creer = new javax.swing.JButton();
        Modifier = new javax.swing.JButton();
        Supprimer = new javax.swing.JButton();
        jLabelMP1 = new javax.swing.JLabel();
        uiCdpost = new javax.swing.JTextField();
        Photo = new javax.swing.JButton();
        avatar = new javax.swing.JLabel();
        message = new javax.swing.JLabel();
        jPanelBt = new javax.swing.JPanel();
        Parametre = new javax.swing.JButton();
        Aide = new javax.swing.JButton();
        Quitter = new javax.swing.JButton();
        Editer = new javax.swing.JButton();
        uiBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("view.UtilCrud");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1080, 680));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 680));
        getContentPane().setLayout(null);

        Entete.setBackground(new java.awt.Color(255,255,255,120));
        Entete.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        Entete.setForeground(new java.awt.Color(255, 0, 0));
        Entete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/java_64.png"))); // NOI18N
        Entete.setText("Gestion des vehicules");
        Entete.setMaximumSize(new java.awt.Dimension(1044, 70));
        Entete.setMinimumSize(new java.awt.Dimension(1044, 70));
        Entete.setOpaque(true);
        Entete.setPreferredSize(new java.awt.Dimension(1044, 70));
        getContentPane().add(Entete);
        Entete.setBounds(0, 0, 1080, 70);

        tbScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        tbScrollPane.setOpaque(false);

        tbUtilisateur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Prénom", "Utilisateur"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbUtilisateur.setOpaque(false);
        tbUtilisateur.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbUtilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUtilisateurMouseClicked(evt);
            }
        });
        tbUtilisateur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbUtilisateurKeyReleased(evt);
            }
        });
        tbScrollPane.setViewportView(tbUtilisateur);
        if (tbUtilisateur.getColumnModel().getColumnCount() > 0) {
            tbUtilisateur.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(tbScrollPane);
        tbScrollPane.setBounds(12, 77, 439, 460);

        jPanelSaisie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSaisie.setForeground(new java.awt.Color(252, 220, 49));
        jPanelSaisie.setOpaque(false);

        jLabelNom.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelNom.setForeground(new java.awt.Color(252, 220, 49));
        jLabelNom.setText("Immatriculation");

        uiNom.setBackground(new java.awt.Color(255,255,255,120));
        uiNom.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiNom.setForeground(new java.awt.Color(255, 255, 255));

        jLabelPrenom.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPrenom.setForeground(new java.awt.Color(252, 220, 49));
        jLabelPrenom.setText("Date d'achat");

        uiPrenom.setBackground(new java.awt.Color(255,255,255,120));
        uiPrenom.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiPrenom.setForeground(new java.awt.Color(255, 255, 255));

        jLabelPseudo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelPseudo.setForeground(new java.awt.Color(252, 220, 49));
        jLabelPseudo.setText("Modele");

        uiPseudo.setBackground(new java.awt.Color(255,255,255,120));
        uiPseudo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiPseudo.setForeground(new java.awt.Color(255, 255, 255));

        jLabelMail.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMail.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMail.setText("Tarif");

        uiMail.setBackground(new java.awt.Color(255,255,255,120));
        uiMail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiMail.setForeground(new java.awt.Color(255, 255, 255));

        jLabelMP.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMP.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMP.setText("Nombre de places");

        uiMP.setBackground(new java.awt.Color(255,255,255,120));
        uiMP.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiMP.setForeground(new java.awt.Color(255, 255, 255));

        uiPhrase.setBackground(new java.awt.Color(255, 255, 255));
        uiPhrase.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        uiPhrase.setForeground(new java.awt.Color(204, 0, 51));

        jLabelMail1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMail1.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMail1.setText("Vitesse maximale");

        uiAdr1.setBackground(new java.awt.Color(255,255,255,120));
        uiAdr1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiAdr1.setForeground(new java.awt.Color(255, 255, 255));
        uiAdr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uiAdr1ActionPerformed(evt);
            }
        });

        Vider.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Vider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/eye-slash_20.png"))); // NOI18N
        Vider.setText("Nouveau");
        Vider.setToolTipText("Dé-selectionner l'utilisateur");
        Vider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViderMouseClicked(evt);
            }
        });

        Creer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Creer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/plus_20.png"))); // NOI18N
        Creer.setText("Creer");
        Creer.setToolTipText("Valider la création d'un nouvel utilisateur");
        Creer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreerMouseClicked(evt);
            }
        });

        Modifier.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/pencil_20.png"))); // NOI18N
        Modifier.setText("Modifier");
        Modifier.setToolTipText("Valider les modifications");
        Modifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModifierMouseClicked(evt);
            }
        });

        Supprimer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/minus_20.png"))); // NOI18N
        Supprimer.setText("Supprimer");
        Supprimer.setToolTipText("Supprimer l'utilisateur");
        Supprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupprimerMouseClicked(evt);
            }
        });

        jLabelMP1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabelMP1.setForeground(new java.awt.Color(252, 220, 49));
        jLabelMP1.setText("Description");

        uiCdpost.setBackground(new java.awt.Color(255,255,255,120));
        uiCdpost.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        uiCdpost.setForeground(new java.awt.Color(255, 255, 255));

        Photo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/user-img_20.png"))); // NOI18N
        Photo.setText("Photo");
        Photo.setToolTipText("Modifier la photographie");
        Photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhotoMouseClicked(evt);
            }
        });

        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/user-tie-min.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanelSaisieLayout = new javax.swing.GroupLayout(jPanelSaisie);
        jPanelSaisie.setLayout(jPanelSaisieLayout);
        jPanelSaisieLayout.setHorizontalGroup(
            jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSaisieLayout.createSequentialGroup()
                        .addComponent(Creer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Modifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Supprimer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Vider))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelMP))
                            .addComponent(jLabelMail1)
                            .addComponent(jLabelMP1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                .addComponent(uiAdr1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(214, 214, 214)
                                .addComponent(uiPhrase, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE))
                            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(uiPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(uiPseudo, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(uiMail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                    .addComponent(uiNom)
                                    .addComponent(uiMP))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(Photo))
                                    .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                                .addComponent(uiCdpost, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelSaisieLayout.setVerticalGroup(
            jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaisieLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiNom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uiPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMail, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uiMail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uiMP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMP, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelSaisieLayout.createSequentialGroup()
                        .addComponent(avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Photo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uiPhrase, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(uiAdr1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelMail1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uiCdpost, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMP1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanelSaisieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vider)
                    .addComponent(Creer)
                    .addComponent(Modifier)
                    .addComponent(Supprimer))
                .addContainerGap())
        );

        getContentPane().add(jPanelSaisie);
        jPanelSaisie.setBounds(469, 77, 580, 460);

        message.setBackground(new java.awt.Color(255, 255, 255));
        message.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        message.setForeground(new java.awt.Color(51, 102, 0));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        message.setText("Message");
        getContentPane().add(message);
        message.setBounds(20, 560, 990, 19);

        jPanelBt.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBt.setMaximumSize(new java.awt.Dimension(1024, 50));
        jPanelBt.setMinimumSize(new java.awt.Dimension(1024, 50));
        jPanelBt.setOpaque(false);
        jPanelBt.setPreferredSize(new java.awt.Dimension(1010, 50));

        Parametre.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Parametre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/wrench._20.png"))); // NOI18N
        Parametre.setText("Paramètre");
        Parametre.setToolTipText("Paramètres de l'application");
        Parametre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ParametreMouseClicked(evt);
            }
        });

        Aide.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Aide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/question-circle_20.png"))); // NOI18N
        Aide.setText("Aide");
        Aide.setToolTipText("Manuel utilisateur");
        Aide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AideMouseClicked(evt);
            }
        });

        Quitter.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/escape_20.png"))); // NOI18N
        Quitter.setText("Quitter");
        Quitter.setToolTipText("Quitter l'application");
        Quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                QuitterMouseClicked(evt);
            }
        });

        Editer.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Editer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/pdf_20.png"))); // NOI18N
        Editer.setText("Pdf");
        Editer.setToolTipText("Envoyer un mail à l'utilisateur");
        Editer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelBtLayout = new javax.swing.GroupLayout(jPanelBt);
        jPanelBt.setLayout(jPanelBtLayout);
        jPanelBtLayout.setHorizontalGroup(
            jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBtLayout.createSequentialGroup()
                .addComponent(Parametre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 652, Short.MAX_VALUE)
                .addComponent(Editer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Aide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Quitter))
        );
        jPanelBtLayout.setVerticalGroup(
            jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Quitter)
                        .addComponent(Aide)
                        .addComponent(Editer))
                    .addComponent(Parametre))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelBt);
        jPanelBt.setBounds(10, 580, 1050, 50);

        uiBackground.setBackground(new java.awt.Color(255, 255, 255));
        uiBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/fec_dark.jpg"))); // NOI18N
        uiBackground.setIconTextGap(0);
        uiBackground.setMaximumSize(new java.awt.Dimension(1060, 660));
        uiBackground.setMinimumSize(new java.awt.Dimension(1060, 660));
        uiBackground.setPreferredSize(new java.awt.Dimension(1060, 660));
        getContentPane().add(uiBackground);
        uiBackground.setBounds(0, 0, 1080, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Positionner les valeurs de la zone de texte 
    private void tbUtilisateurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUtilisateurMouseClicked
        // TODO add your handling code here:
        changeSelectUt();
    }//GEN-LAST:event_tbUtilisateurMouseClicked

        private void CreerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreerMouseClicked
            // TODO add your handling code here:
            // mise à jour de la liste
            if (lesUtilisateurs.get(uiPseudo.getText().strip()) != null) {
                alert("Utilisateur déjà existant ; veuillez choisir un autre pseudo.");
                return;
            }
            if ("".equals(uiNom.getText().strip()) || "".equals(uiMP.getText().strip())) {
                alert("Saisir au moins un nom et un mot de passe.");
                return;
            }
            if ("".equals(uiCdpost.getText().strip()) || "".equals(uiNumpost)) {
                alert("Saisir le code postal et renseigner la ville.");
                return;
            }
            // création de l'utilisateur
            Utilisateur unUtilisateur = new Utilisateur();
            unUtilisateur.setUtPseudo(uiPseudo.getText().strip());
            unUtilisateur.updateUtMp(uiMP.getText().strip());
            uiPhrase.setText(unUtilisateur.getUtPhrase());
            unUtilisateur.setUtNom(uiNom.getText().strip());
            unUtilisateur.setUtPrenom(uiPrenom.getText().strip());
            unUtilisateur.setUtMail(uiMail.getText().strip());
            unUtilisateur.setUtAdr1(uiAdr1.getText().strip());
          //  unUtilisateur.setUtAdr2(uiAdr2.getText().strip());
            unUtilisateur.utCommune.setCode_Postal(uiCdpost.getText().strip());
            unUtilisateur.utCommune.setNum_Postal(uiNumpost);
         //   unUtilisateur.utCommune.setNom_Commune(uiCommune.getText());
            // Ajout à la liste
            lesUtilisateurs.put(unUtilisateur.getUtPseudo(), unUtilisateur);
            // MàJ des données du tableau
            chargerTableauUtilisateurs();
            // mise à jour de la bd
            dao.create(unUtilisateur);


        }//GEN-LAST:event_CreerMouseClicked

        private void ViderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViderMouseClicked
            // TODO add your handling code here:
            tbUtilisateur.getSelectionModel().clearSelection();
            message.setText("Vous pouvez saisir un nouvel utilisateur !");
            viderSaisie();
        }//GEN-LAST:event_ViderMouseClicked

        private void QuitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_QuitterMouseClicked
            // TODO add your handling code here:
           this.dispose();
        }//GEN-LAST:event_QuitterMouseClicked

        private void AideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AideMouseClicked
            // TODO add your handling code here:
        }//GEN-LAST:event_AideMouseClicked

        private void ParametreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ParametreMouseClicked
            // TODO add your handling code here:
            Parametre parametre = new Parametre(this.utConnect);
            parametre.setVisible(true);
        }//GEN-LAST:event_ParametreMouseClicked

        private void ModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModifierMouseClicked
            // TODO add your handling code here:

            // mise à jour de la liste
            int i = tbUtilisateur.getSelectedRow();
            if (i < 0) {
                alert("Aucune donnée n'est selectionnée en modification ; veuillez choisir un utilisateur.");
                return;
            }
            TableModel model = tbUtilisateur.getModel();
            Utilisateur unUtilisateur = lesUtilisateurs.get(model.getValueAt(i, 2).toString().strip());
            if (!unUtilisateur.getUtPseudo().equals(uiPseudo.getText().strip())) {
                alert("Vous ne pouvez pas modifier le pseudo de l'utilisateur (creez en un autre puis supprimez l'ancien). ("
                        + unUtilisateur.getUtPseudo() + "/" + uiPseudo.getText().strip() + ")");
                return;
            }
            // le mot de passe a t-il changé ?
            if (!unUtilisateur.getUtMp().equals(uiMP.getText().strip())) {
                System.out.println("\n 1=" + unUtilisateur.getUtMp() + "\n 2=" + uiMP.getText().strip());
                unUtilisateur.updateUtMp(uiMP.getText().strip());
                uiPhrase.setText(unUtilisateur.getUtPhrase());
            }
            // MàJ les données de l'objet utilisateur
            unUtilisateur.setUtNom(uiNom.getText().strip());
            unUtilisateur.setUtPrenom(uiPrenom.getText().strip());
            unUtilisateur.setUtMail(uiMail.getText().strip());
            //unUtilisateur.setUtMp(uiMP.getText().strip());
            unUtilisateur.setUtAdr1(uiAdr1.getText().strip());
         //   unUtilisateur.setUtAdr2(uiAdr2.getText().strip());
            unUtilisateur.utCommune.setCode_Postal(uiCdpost.getText().strip());
            unUtilisateur.utCommune.setNum_Postal(uiNumpost);
        //    unUtilisateur.utCommune.setNom_Commune(uiCommune.getText());
            // MàJ des données du tableau
            model.setValueAt(uiNom.getText(), i, 0);
            model.setValueAt(uiPrenom.getText(), i, 1);
            // mise à jour de la bd
            dao.update(unUtilisateur);

        }//GEN-LAST:event_ModifierMouseClicked

    private void tbUtilisateurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbUtilisateurKeyReleased
        // TODO add your handling code here:
        changeSelectUt();
    }//GEN-LAST:event_tbUtilisateurKeyReleased

    private void SupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupprimerMouseClicked
        // TODO add your handling code here:
        int i = tbUtilisateur.getSelectedRow();
        if (i < 0) {
            alert("Aucune donnée n'est selectionnée; veuillez selectionner l'utilisateur a supprimer.");
            return;
        }
        DefaultTableModel uiTable = (DefaultTableModel) tbUtilisateur.getModel();
        String pseudo = uiTable.getValueAt(i, 2).toString();
        // mise à jour de la bd
        dao.delete(pseudo);
        uiTable.removeRow(i);
        lesUtilisateurs.remove(pseudo);
        viderSaisie();
    }//GEN-LAST:event_SupprimerMouseClicked

    private void EditerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditerMouseClicked

    private void PhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhotoMouseClicked
        // TODO add your handling code here:
        String pseudo = uiPseudo.getText().strip();
        int i = tbUtilisateur.getSelectedRow();
        if (pseudo.isEmpty() || i < 0) {
            alert("Pour lui attacher une photo, l'utilisateur doit exister.");
        } else {
            SelectAvatar selPhoto = new SelectAvatar(new javax.swing.JFrame(), true, pseudo);
            selPhoto.setVisible(true);
            if (selPhoto.isSelected()) {
                chargePhotoUt();
            }
            selPhoto = null;
        }
    }//GEN-LAST:event_PhotoMouseClicked

    private void uiAdr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uiAdr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uiAdr1ActionPerformed

    // methode pour changer d'utilisateur
    public void changeSelectUt() {
        // pointer sur le colonne selectionnée
        int i = tbUtilisateur.getSelectedRow();
        //System.out.println("selected row=" + i);
        // récupérer les données de l'utilisateur
        // utiliser les données du tableau ou ...
        TableModel model = tbUtilisateur.getModel();
        Utilisateur unUtilisateur = lesUtilisateurs.get(model.getValueAt(i, 2).toString());
        uiNom.setText(unUtilisateur.getUtNom());
        uiPrenom.setText(unUtilisateur.getUtPrenom());
        uiPseudo.setText(unUtilisateur.getUtPseudo());
        uiMail.setText(unUtilisateur.getUtMail());
        uiMP.setText(unUtilisateur.getUtMp());
        uiPhrase.setText(unUtilisateur.getUtPhrase());
        uiAdr1.setText(unUtilisateur.getUtAdr1());
    //    uiAdr2.setText(unUtilisateur.getUtAdr2());
        uiCdpost.setText(unUtilisateur.utCommune.getCode_Postal());
        uiNumpost = unUtilisateur.utCommune.getNum_Postal();
    //    uiCommune.setText(unUtilisateur.utCommune.getNom_Commune());
        chargePhotoUt();
    }

    private void chargePhotoUt() {
        this.photo = new Photo();
        photoDAO.getUtIcon(this.uiPseudo.getText().strip(),photo);
        this.avatar.setIcon(photo.getMiniatureIcon());
        this.photo = null;
    }

    // methode pour afficher un message
    public void alert(String msg) {
        JOptionPane.showMessageDialog(rootPane, msg);
        message.setForeground(new java.awt.Color(51, 102, 0));
        message.setText(msg);
    }

    // methode  to show an error alert
    public void alert(String msg, String titre) {
        JOptionPane.showMessageDialog(rootPane, msg, titre, JOptionPane.ERROR_MESSAGE);
        message.setForeground(new java.awt.Color(204, 0, 51));
        message.setText(msg);
    }

    //delete details in the db
    public void delete(String pseudo) {

    }

    // methode pour vider les champs de texte de l'écran
    private void viderSaisie() {
        uiNom.setText("");
        uiPrenom.setText("");
        uiPseudo.setText("");
        uiMail.setText("");
        uiMP.setText("");
        uiPhrase.setText("");
        uiAdr1.setText("");
    //    uiAdr2.setText("");
        uiCdpost.setText("");
        uiNumpost = "";
    //    uiCommune.setText("");
        avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressource/user-tie-min.jpg")));

    }

    // chargerLesUtilisateurs 
    private void chargerLesUtilisateurs() {

        lesUtilisateurs.clear();
        lesUtilisateurs = UtilisateurDAO.getLesUtilisateurs();
        chargerTableauUtilisateurs();
    }

    private void chargerTableauUtilisateurs() {

        DefaultTableModel uiTable = (DefaultTableModel) tbUtilisateur.getModel();
        int j = uiTable.getRowCount();
        //System.out.println("Row count=" + j);
        for (int i = j - 1; i >= 0; i--) {
            //System.out.println("Row remove=" + i);
            uiTable.removeRow(i);
        }
        int i = 0;
        for (String pseudo : lesUtilisateurs.keySet()) {
            Utilisateur unUtilisateur = lesUtilisateurs.get(pseudo);
            Object[] row = new Object[3];
            row[0] = unUtilisateur.getUtNom();
            row[1] = unUtilisateur.getUtPrenom();
            row[2] = unUtilisateur.getUtPseudo();

            uiTable.addRow(row);
            if(pseudo.equals(uiPseudo.getText().strip())) {
                tbUtilisateur.setRowSelectionInterval(i, i);
            }
            i++;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aide;
    private javax.swing.JButton Creer;
    private javax.swing.JButton Editer;
    private javax.swing.JLabel Entete;
    private javax.swing.JButton Modifier;
    private javax.swing.JButton Parametre;
    private javax.swing.JButton Photo;
    private javax.swing.JButton Quitter;
    private javax.swing.JButton Supprimer;
    private javax.swing.JButton Vider;
    private javax.swing.JLabel avatar;
    private javax.swing.JLabel jLabelMP;
    private javax.swing.JLabel jLabelMP1;
    private javax.swing.JLabel jLabelMail;
    private javax.swing.JLabel jLabelMail1;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelPrenom;
    private javax.swing.JLabel jLabelPseudo;
    private javax.swing.JPanel jPanelBt;
    private javax.swing.JPanel jPanelSaisie;
    private javax.swing.JLabel message;
    private javax.swing.JScrollPane tbScrollPane;
    private javax.swing.JTable tbUtilisateur;
    private javax.swing.JTextField uiAdr1;
    private javax.swing.JLabel uiBackground;
    private javax.swing.JTextField uiCdpost;
    private javax.swing.JTextField uiMP;
    private javax.swing.JTextField uiMail;
    private javax.swing.JTextField uiNom;
    private javax.swing.JLabel uiPhrase;
    private javax.swing.JTextField uiPrenom;
    private javax.swing.JTextField uiPseudo;
    // End of variables declaration//GEN-END:variables
}
